add new doc repo

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -1,6 +1,15 @@
-name: Docs
+name: docs
 
-on: [push, pull_request]
+on:
+  push:
+    branches:
+      - main
+    paths:
+      - 'docs/**'
+      - '**.rst'
+      - '**/docs.yml'
+  schedule:
+    - cron: "30 4 * * *"
 
 jobs:
   build:
@@ -9,11 +18,14 @@ jobs:
     steps:
       - uses: actions/checkout@v3
         with:
+          token: ${{ secrets.OSQ_REPO_TOKEN }}
           submodules: "recursive"
+
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: 3.9
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
@@ -22,16 +34,6 @@ jobs:
       - name: Build docs
         run: |
           tox -e docs
-
-      - name: Slack Notification
-        uses: homoluctus/slatify@master
-        if: failure()
-        with:
-          type: ${{ job.status }}
-          job_name: '*Docs*'
-          commit: true
-          url: ${{ secrets.SLACK_BUILD_WEBHOOK }}
-          token: ${{ secrets.SLACK_GITHUB_TOKEN }}
 
       - name: Preserve Docs
         if: ${{ github.event_name == 'push' }}
@@ -50,8 +52,8 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     env:
-      DOCS_REPO: platformio/platformio-docs
-      DOCS_DIR: platformio-docs
+      DOCS_REPO: OS-Q/doc
+      DOCS_DIR: docs
       LATEST_DOCS_DIR: latest-docs
       RELEASE_BUILD: ${{ startsWith(github.ref, 'refs/tags/v') }}
     if: ${{ github.event_name == 'push' }}
@@ -72,10 +74,11 @@ jobs:
         id: get-destination-dir
         run: |
           if [[ ${{ env.RELEASE_BUILD }} == true ]]; then
-            echo "::set-output name=dst_dir::stable"
+            echo "::set-output name=dst_dir::/stable"
           else
-            echo "::set-output name=dst_dir::latest"
+            echo "::set-output name=dst_dir::/"
           fi
+
       - name: Checkout latest Docs
         continue-on-error: true
         uses: actions/checkout@v3
@@ -83,27 +86,29 @@ jobs:
           repository: ${{ env.DOCS_REPO }}
           path: ${{ env.DOCS_DIR }}
           ref: gh-pages
+
       - name: Synchronize Docs
         run: |
           rm -rf ${{ env.DOCS_DIR }}/.git
-          rm -rf ${{ env.DOCS_DIR }}/en/${{ steps.get-destination-dir.outputs.dst_dir }}
-          mkdir -p ${{ env.DOCS_DIR }}/en/${{ steps.get-destination-dir.outputs.dst_dir }}
-          cp -rf ${{ env.LATEST_DOCS_DIR }}/html/* ${{ env.DOCS_DIR }}/en/${{ steps.get-destination-dir.outputs.dst_dir }}
+          rm -rf ${{ env.DOCS_DIR }}/pio${{ steps.get-destination-dir.outputs.dst_dir }}
+          mkdir -p ${{ env.DOCS_DIR }}/pio${{ steps.get-destination-dir.outputs.dst_dir }}
+          cp -rf ${{ env.LATEST_DOCS_DIR }}/html/* ${{ env.DOCS_DIR }}/pio${{ steps.get-destination-dir.outputs.dst_dir }}
           if [[ ${{ env.RELEASE_BUILD }} == false ]]; then
-            rm -rf ${{ env.DOCS_DIR }}/page
-            mkdir -p ${{ env.DOCS_DIR }}/page
-            cp -rf ${{ env.LATEST_DOCS_DIR }}/rtdpage/* ${{ env.DOCS_DIR }}/page
+            rm -rf ${{ env.DOCS_DIR }}/pio/page
+            mkdir -p ${{ env.DOCS_DIR }}/pio/page
+            cp -rf ${{ env.LATEST_DOCS_DIR }}/rtdpage/* ${{ env.DOCS_DIR }}/pio/page
           fi
+
       - name: Validate Docs
         run: |
           if [ -z "$(ls -A ${{ env.DOCS_DIR }})" ]; then
-             echo "Docs folder is empty. Aborting!"
-             exit 1
+            echo "Docs folder is empty. Aborting!"
+            exit 1
           fi
       - name: Deploy to Github Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
-          personal_token: ${{ secrets.DEPLOY_GH_DOCS_TOKEN }}
+          personal_token: ${{ secrets.OSQ_REPO_TOKEN }}
           external_repository: ${{ env.DOCS_REPO }}
           publish_dir: ./${{ env.DOCS_DIR }}
           commit_message: Sync Docs
